using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Anmeldelser
{
    internal class Repository
    {
        public List<String> GetReviews()
        {
            return new List<String>
            {
                "I recently purchased the XYZ-1000 wireless earbuds, and I am thoroughly impressed with their performance. The sound quality is exceptional, with deep bass and clear treble, making my music and podcasts sound fantastic. The noise-canceling feature is also highly effective, allowing me to focus on my work without being disturbed by background noise. The earbuds are comfortable to wear for extended periods, and the battery life is outstanding, lasting me through a full day of use with no issues.\r\n\r\nThe only downside I noticed is the touch controls, which can be a bit sensitive and sometimes register unintended commands. However, this is a minor inconvenience compared to the overall quality and performance of these earbuds. The sleek design and compact charging case make them easy to carry around. I would highly recommend the XYZ-1000 to anyone looking for high-quality wireless earbuds at a reasonable price.",
                "The smart home security camera I bought has exceeded my expectations in terms of both performance and ease of use. Setting it up was a breeze, thanks to the intuitive app and clear instructions. The camera provides crystal-clear video quality, both during the day and at night, with its excellent infrared night vision. I can easily monitor my home from anywhere using my smartphone, which gives me great peace of mind.\r\n\r\nOne feature I particularly appreciate is the motion detection alerts, which notify me immediately if any movement is detected. This has proven to be very reliable and has helped me feel more secure. The two-way audio function is also a nice touch, allowing me to communicate with anyone at my door without having to open it. Overall, this security camera is a fantastic investment for anyone looking to enhance their home security.",
                "I decided to switch to eco-friendly bamboo toothbrushes, and I couldn't be happier with my choice. These toothbrushes are not only sustainable but also very effective. The bristles are soft yet sturdy enough to provide a thorough clean without irritating my gums. The bamboo handle is smooth and comfortable to hold, and I love knowing that it is biodegradable and won't contribute to plastic waste.\r\n\r\nThe packaging is also environmentally friendly, which is a big plus for me. Each toothbrush is individually wrapped in recyclable paper, eliminating the need for plastic. The toothbrushes come in a pack of four, which is very convenient and cost-effective. I highly recommend these bamboo toothbrushes to anyone looking to make a small but meaningful change towards a more sustainable lifestyle.",
                "I recently purchased the ABC-500 Bluetooth speaker, and I must say I'm quite disappointed with its performance. The sound quality is far from what I expected, with the bass being almost non-existent and the overall audio lacking clarity. Even at moderate volumes, the sound becomes distorted, making it difficult to enjoy music or podcasts. I had high hopes for this speaker, given its positive reviews, but it seems it fell short in my experience.\r\n\r\nAdditionally, the battery life is another letdown. The product description claimed it could last up to 10 hours, but I found it struggling to make it past 5 hours with continuous use. The Bluetooth connectivity is also unstable, frequently disconnecting from my devices without any apparent reason. The build quality feels cheap, and the buttons are unresponsive at times. Overall, I would not recommend the ABC-500 Bluetooth speaker to anyone looking for a reliable and high-quality audio experience.",
                 "The DEF-700 electric kettle has been quite a disappointment for me. From the very beginning, it emitted a strange plastic smell whenever I used it, which didn't seem to go away even after several boils. This made me concerned about the safety and quality of the materials used in its construction. Additionally, the kettle takes an unusually long time to boil water compared to my previous one, which is quite frustrating when I'm in a hurry.\r\n\r\nThe design of the kettle is also flawed. The spout tends to drip water every time I pour, creating a mess on my kitchen counter. The lid doesn't fit securely, which can be dangerous when handling boiling water. Furthermore, the kettle's exterior gets extremely hot to the touch, posing a burn risk. Overall, the DEF-700 electric kettle has been a regretful purchase, and I would advise others to look for a more reliable and safer option."
            };
        }
    }
}
